### ISSUE TITLE
Add missing documentation for the SimpleActuators module

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/hac-game-lib#14]
In gamelib.Actuators.SimpleActuators the following classes are insufficiently documented:
- RandomActuator
- PathActuator

**Comment by Dansyuqri** [comment]
Hello! I am new to open source but I would like to take on this task!

**Comment by arnauddupuis** [comment]
Absolutely!

First of all, welcome to the open source community. 
The PathActuator's description was added yesterday. We still need formal documentation on each function as well as documentatio for the RandomActuator.
In the SimpleActuators module we need documentation for:

- PatrolActuator.next_move()
- PathActuator.next_move()
- PathActuator.set_path()
- RandomActuator.next_move()

The template I'm using for documentation is the following:
```
        """ Short description

        Long description or details to add to the short description (if needed)

        :param name: some param
        :type name: str
        
        Example::
        
            method()

        """
```
The documentation is written using restructuredText doc strings.

Feel free to send your pull requests! I really appreciate the help.
