### ISSUE TITLE
Improve Utils.get_key()

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/hac-game-lib#27]
**Problem summary:**  
The current implementation of get_key() read one character from stdin and returns it. However, some keyboard's keys are actually using 2 characters (like the keyboard arrows).

**Expected behavior:**  
We should be able to use any key on the keyboard, not only the one that encode in 1 character.

**Work to do:**  
Make it possible to use 2 characters coded keys. At least the arrows.  
It is also probably a good idea to add constants to the Constants module for specific keys (like ALT, CTRL, SHIFT or arrow keys).

**Comment by Dansyuqri** [comment]
Hi, I am still looking at alternative solutions, but can I take a go at solving this?

**Comment by arnauddupuis** [comment]
Of course you can! Thanks for helping!

My philosophie is to be dependent only from Python. Still Colorama is a dependency but it's a pure python implementation of terminal colors.
The thing we should probably avoid for now is dependencies like curse, however I'm obviously open to suggestions. What do you have in mind?

**Comment by kaozdl** [comment]
Here you have a similar implementation of the same issue in C
Usually keys that send more than one byte send an escape sequence.
you can ask for the first char and read 2 additional bytes from stdin.
https://github.com/kaozdl/ken/blob/23286636805ecc330f9a44f243d55ec2e00e98a3/ken.c#L141

**Comment by arnauddupuis** [comment]
That's a valid approach yes. 
Once that is done we need to take care of making that specific function multi platform (it's the only one that is Linux specific). But I'll add a dedicated issue that depend on this one.

**Comment by Dansyuqri** [comment]
@arnauddupuis What I had in mind initially was to use the [pynput](https://pynput.readthedocs.io/en/latest/) package. However, there are limitations to that, particularly requiring [root access for some platforms](https://pynput.readthedocs.io/en/latest/limitations.html).

I will try with the reading first and read additional input approach as for now and work from there with making it multi platform. 

Thanks for the suggestion @kaozdl !
