### ISSUE TITLE
Fix the map selection in hgl-editor

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/hac-game-lib#3]
The first screen of the hgl-editor is the map selection however it is using Utils.get_key() to get the number of the map to load (https://hac-game-lib.readthedocs.io/en/latest/utils.html#gamelib.Utils.get_key).

The problem is when you have more than 10 maps: you can't select the one after number 9.
This issue is really simple to fix: it require to change the call to Utils.get_key() to a standard input() call.
This is typically an issue for new programmers or new contributors.

**Comment by gunjanraval** [comment]
Every call of Utils.get_key() needs to be changed to input()?

**Comment by arnauddupuis** [comment]
Good catch!
No, only these ones:
https://github.com/arnauddupuis/hac-game-lib/blob/path-finding-improvements/hgl-editor.py#L405

The other place where it could be useful is when the current_menu == "boards_list". It's slightly more complex as it require to not use the key variable but create a workflow by itself. I'll make a separate issue for this (as it requires also to support going back to the main menu).
