### ISSUE TITLE
[BUG] Saving the wrong file in hgl-editor

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/hac-game-lib#31]
**Describe the bug**
One o the recent changes introduced a bug in hgl-editor: when working on a map and selecting  
> L - Save this Board and load a new one

The editor does load the new map but the file to it to is not changed and remains the file name of the previously loaded map.

**To Reproduce**
1. Start hgl-editor.
2. Load a map.
3. Select "L - Save this Board and load a new one"
4. Look at "S - Save the current Board to [map file name]" -> it is the previous map file name

**Expected behavior**
The map file name is updated every time a new map is loaded so it is saved in the right file.

**Screenshots**
At the top we can see that the current board is _Debug Board_ and the filename is still _House_Inside.json_ (should be Debug_Board.json).
![Screenshot_20191006_092621_hgl-editor_bug](https://user-images.githubusercontent.com/787155/66272199-7703a780-e81b-11e9-9954-b0886aa2a009.png)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 29
 - Python version 3.7.4

**Additional context**
None

**Comment by gunjanraval** [comment]
I tried to reproduce and found out that the same board name is only displayed but on saving I'm getting the actual board name

**Comment by arnauddupuis** [comment]
Yes but it saves the board in the wrong file.

**Comment by gunjanraval** [comment]
I think I got it
