### ISSUE TITLE
[BUG] hgl-editor back menu is added every time the board_list is displayed (when we come back to the main menu).

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/hac-game-lib#34]
**Describe the bug**
The back key is added every time the user comes back from the boards_list menu.

**To Reproduce**
1. Start hgl-editor
2. Load any map
3. Hit 'L' to load a new map
4. Hit 'B' to come back to the main menu
5. Hit 'L' again, there is now 2 menu entries for 'B - Go Back to main menu'
6. Each time you come back to the boards_list menu a new menu entry is added.

**Expected behavior**
Only one back menu entry should appear at all time.

**Screenshots**
![Screenshot_20191006_092621_hgl-editor_bug-back-menu](https://user-images.githubusercontent.com/787155/66330456-4a1bc700-e8e5-11e9-8cce-17743b48a661.png)

**Desktop (please complete the following information):**
 - OS: Fedora 29
 - Python version 3.7.4

**Additional context**
It's only a problem of where the menu entry is added. All thing considered, building the boards_list menu should be a function that clears the existing category from all menu entries (or delete the entire category and recreate it), get the files on disk (in case it changed) and add the back menu entry at the end. The back menu entry should not be added in the main loop (unless we check for existence first but it's probably not the best way to do it in the main loop).

**Comment by ziebam** [comment]
I can take a shot at this issue if that's okay.

**Comment by arnauddupuis** [comment]
Of course! Thanks for your help!

**Comment by arnauddupuis** [comment]
Not at all, it's a Python module that works everywhere. You can definitely work on it from Windows.

**Comment by ziebam** [comment]
It raises numerous errors because of `termios` module which is Unix-only.

**Comment by synackray** [comment]
Thanks for helping give children the opportunity to learn coding. I'm glad to have come across this project on the hackathon board. Keep up the good work.

**Comment by arnauddupuis** [comment]
@synackray Thank you for your contribution! And thanks for the praise!

@ziebam you are absolutely right! My bad, changing the code of get_key() to make it multi-platform has been on my todo forever... I'll take care of it.
