### ISSUE TITLE
Run flake8 on the project

### ISSUE THREAD

**Issue by kaozdl** [arnauddupuis/hac-game-lib#39]
after installing flake8 it reveals a lot of linting issues in the code.
Since the PR's will take a lot of lines from a lot of files just open the issues regarding this.
When flake8 passes this issue will be closed

steps to reproduce:
- install dev dependencies with `pipenv install --dev`
- run `flake8 .` at top level

**Comment by arnauddupuis** [comment]
That's a much needed one.

**Comment by 0xecho** [comment]
I can get on this one :-)

**Comment by arnauddupuis** [comment]
Just make sure @kaozdl haven't started to work on that ;)

**Comment by kaozdl** [comment]
go ahead.
Try to make separate PR's for each file.
If not it will be huge

**Comment by f-osorio** [comment]
I can work on this too. I can start with `examples/`, unless someone else has already started.

**Comment by guilleijo** [comment]
I can work on this too. I'm going to start with `./hgl-base_game.py`

**Comment by kaozdl** [comment]
please name your branches as fix_flake8/<file_name>

**Comment by kaozdl** [comment]
@f-osorio go ahead!

**Comment by Eyansky** [comment]
How about introducing flake8 check on every pr on circleci?

**Comment by kaozdl** [comment]
@Eyansky yeah, that's desirable for sure. 
Go ahead

**Comment by arnauddupuis** [comment]
I'll work on:
- Actuators/Actuator.py
- Actuators/SimpleActuators.py
- Actuators/AdvancedActuators.py
