### ISSUE TITLE
Integrate circleci with the project

### ISSUE THREAD

**Issue by kaozdl** [arnauddupuis/hac-game-lib#45]
Since we now have unit tests it would be nice to have circle-ci integrated with the project.
Circle CI should:
- run all tests
- check for flake8 violations.

You can refer to the circleci docs about integrating it to python projects.
https://circleci.com/docs/2.0/language-python/

**Comment by spassarop** [comment]
I could grab this one :)

**Comment by spassarop** [comment]
This PR includes the CircleCI configuration file that builds the environment, runs flake8 with default rules and runs the tests under `tests` folder :)
