### ISSUE TITLE
Create a Projectile object

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/hac-game-lib#6]
We need a base class to create different types of projectiles.

The gamelib.Projectile needs to have the following features:

- Be a sub-class of BoardItem.
- Have a multi model system (so it can change based on movements or collision).
- Have a callback system likely similar to GenericActionnableStructure (https://hac-game-lib.readthedocs.io/en/latest/structures.html#gamelib.Structures.GenericActionableStructure and https://github.com/arnauddupuis/hac-game-lib/blob/master/gamelib/Structures.py)
- Have a round counter to automatically disappear or to have a maximum range.

We probably need to add the specific case of Projectiles in Board.move() (https://github.com/arnauddupuis/hac-game-lib/blob/master/gamelib/Board.py#L219).

This is not a trivial issue.

**Comment by kaozdl** [comment]
Can you give me a bit more context?
For point 2 mostly

**Comment by arnauddupuis** [comment]
Absolutely, sorry this issue is not really detailed indeed.
The idea here is to create a base class for all kind of projectiles (magic fireball, bullets, healing spells, etc.).
The way I was thinking of it is: 
- Any BoardItem can throw a projectile (Player, NPC or any structure that could be a trap).
- When a BoardItem shoots a projectile the projectile travels trough a predetermined path.
- When a projectile touches something it should trigger its action callback.
- The projectile should be able to have multiple models to simulate evolution. I'll give a specific example just after.
- The projectile should be able to have a limit in term of range (practically speaking: a limited number of round of existence) and when its maximum range is reached either trigger the callback or not based on a configurable boolean (a bit like the circle_waypoints member in PathFinder).

In [examples/tutorials/03-game-design/99-final-game.py](https://github.com/arnauddupuis/hac-game-lib/blob/master/examples/tutorials/03-game-design/99-final-game.py), the bombs in the maze are kind of animated: when you walk on it they appear then explode (and damage the player). I think we should actually have an Animation class (or FrameSet whatever the name) and the Projectile class should use it. The Animation class could offer a play_all() and play_step() type of API that the projectile can leverage while it is traveling (play_step()) or while being triggered (play_all())
For example, if a NPC throw a laser, the laser could be green for the 3 first cells, orange for the 3 next, red for the last 2 one and then explode. It gives the developers the possibility to show a pattern to the gamer. It also gives him the simple possibility to make it look nice and animated.
Particularly in the wake of multi-threading capabilities.

Give me your opinion I'll add the Animation class issue and can take care of it. It's on my todo list anyway.

Is that clearer now?

**Comment by kaozdl** [comment]
yeah it definitely is.
i think we can use some sort of state pattern to model this behavior.
So a projectile can behave differently in different stages of its life.
So we can intitialize the Class and add a next_step() method.
Each step can be a dict with an icon, and attributes that apply to that class dynamically.
```python

class Projectile(BoardItem):
    def __init__(self, states, default_state=0):
        super().__init__()
        current_state = states[0]
        self.current_state = default_state
        self.states = states
        for attr, value in current_state.items():
             setattr(self,attr,value)
    
     def next_state(self):
           for attr in self.current_state.keys():
                del(self.__dict__[attr])
           if self.current_state <= len(self.states):
               self.current_state += 1:
        for attr, value in current_state.items():
             setattr(self,attr,value)
```

**Comment by arnauddupuis** [comment]
That could definitely work! 
It is also an extremely interesting idea to add a state machine to the library. The main goal is to help teach Python to kids and beginners and when they advance have them look at the library code to find more challenging problems and solutions. In that regard, we were definitely lacking a state machine.

**Comment by arnauddupuis** [comment]
I am also working on the Animation class as it is probably needed somewhere else anyway ;)

**Comment by arnauddupuis** [comment]
And just to be clear, I agree with you on the fact that each state should have its own model. It's a lot better than what I suggested.

**Comment by kaozdl** [comment]
Ok. i'll issue a pr then

**Comment by arnauddupuis** [comment]
:+1:

**Comment by kaozdl** [comment]
Issued PR for finite state machine.
Once that is done i can continue with this

**Comment by arnauddupuis** [comment]
Done in e8f12208ac6df05c2613801ec3d9f0c3a308e2b7
