### ISSUE TITLE
Fix the map loading from main screen in hgl-editor

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/hac-game-lib#9]
In the main screen, it is possible to save and load a new map/board. 
However this suffer from the same problem than issue #3.

So when the current_menu is equal to "boards_list" instead of using the _key_ variable, we should create a workflow where:
- The list is displayed (no change)
- Instead of using the _key_ variable, use input() to get the number of the map to load
- Add an entry to go back to the main menu

**Comment by kaozdl** [comment]
i've took a shot at this.

**Comment by arnauddupuis** [comment]
Thanks, I'll merge your PR.
Now what's left is for me to merge your other PR about directories and use the directories.json here too.

Thank you very much for your contributions.

**Comment by kaozdl** [comment]
i think this one is closed isn't it?
Is there anything left to do?

**Comment by arnauddupuis** [comment]
No you're right I don't know why it wasn't close with the last merge. My fault probably.
